Require needed ActiveSupport core extensions (#283)
## Description

When using the CableReady gem (or the `cable_ready-element` gem to be
specific) outside of a Rails context it was complaining about undefined
methods for:

```
NoMethodError: undefined method `seconds' for 0.1:Float
    rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cable_ready-5.0.1/lib/cable_ready/config.rb:31:in `initialize'
```
and
```
NoMethodError: undefined method `many?' for [{:message=>"Test"}]:Array
    rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cable_ready-5.0.1/lib/cable_ready/operation_builder.rb:41:in `block in add_operation_method'
```

Requiring the right ActiveSupport core extensions resolves those errors.

## Why should this be added

This makes the gem more portable and less Rails-dependent.